apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
          ports:
            - name: pgport
              containerPort: 5432
              protocol: TCP
          image: "postgres:latest"
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
