apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: pgport
      port: 5432
      protocol: TCP
      targetPort: pgport
  type: ClusterIP
