apiVersion: v1
kind: Secret
metadata:
  name: torgi-bot
  labels:
    app: torgi-bot
stringData:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "password"
  DB_DATABASE: "postgres"
  DB_SCHEMA: "public"
  TELEGRAM_CHAT_ID: "{{ .Values.telegram.chat_id }}"
  TELEGRAM_TOKEN: "{{ .Values.telegram.token }}"