apiVersion: v1
kind: Secret
metadata:
  name: torgi-bot
  labels:
    app: torgi-bot
stringData:
  DB_HOST: "host.docker.internal"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "password"
  DB_DATABASE: "postgres"
  DB_SCHEMA: "public"
  TG_CHANNEL_ID: "{{ .Values.TG_CHANNEL_ID }}"
  TG_THREAD_ID: "{{ .Values.TG_THREAD_ID }}"
  TG_BOT_TOKEN: "{{ .Values.TG_BOT_TOKEN }}"
